# Generated by Django 4.2.3 on 2023-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={"verbose_name": "Сделка", "verbose_name_plural": "Сделки"},
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                fields=("customer", "date"), name="unique_customer_date"
            ),
        ),
    ]
