# Generated by Django 4.2.3 on 2023-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0002_alter_deal_options_deal_unique_customer_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deal",
            name="unique_customer_date",
        ),
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.CharField(max_length=100, verbose_name="Username покупателя"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="date",
            field=models.DateTimeField(verbose_name="Дата и время регистрации сделки"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="item",
            field=models.CharField(max_length=100, verbose_name="Наименование товара"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество товара, шт"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="total",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Сумма сделки"
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                fields=("customer", "date"),
                name="unique_deal",
                violation_error_message="Сделка клиента “%(customer)s” на “%(date)s” уже существует.",
            ),
        ),
    ]
